# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# NVIDIA environment variables (set by Omarchy):
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,iHD  # was previously set to nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Processing: move to top right
windowrule = move monitor_w-window_w 36, match:class processing-core-PApplet

unbind = SUPER, K
unbind = SUPER, J
binde = SUPER, H, moveactive, -20 0
binde = SUPER, J, moveactive, 0 20
binde = SUPER, K, moveactive, 0 -20
binde = SUPER, L, moveactive, 20 0
